"""empty message

Revision ID: 6d28e5390cbc
Revises: 7abeb3e3aeaf
Create Date: 2025-01-16 11:35:14.394604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d28e5390cbc'
down_revision = '7abeb3e3aeaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
